### ISSUE TITLE
Any chance of transferring the `pipx` name on PyPI to another project?

### ISSUE THREAD

**Issue by ncoghlan** [khalti/pipx#2]
Hi folks,

Thanks for making an attempt at improving the state of the art in Python packaging, even if you ultimately decided to move on to other things.

We've recently had a [pull request](https://github.com/pypa/python-packaging-user-guide/pull/594) come in https://packaging.python.org that adds a guide on using the https://github.com/pipxproject/pipx-app project to manage Python executable as isolated applications, and one of the potential points of confusion I noted is that `pip install --user pipx` won't actually work the way folks might expect.

So what I was wondering is, assuming you aren't planning to pursue your own `pipx` project further, whether you might be willing to transfer the `pipx` name on PyPI over to @cs01 such that users will have the freedom to choose between managing `pipx` with itself as a standalone application (via `pipx-bootstrap`), or using the more traditional approach of running `pip install --user pipx` and managing it as a regular Python package.

**Comment by ncoghlan** [comment]
(Note: I hadn't seen https://github.com/pipxproject/pipx-app/issues/2 when I filed this, but even given that, I think enough has changed since the original discussion to revisit the request)

**Comment by ludbek** [comment]
Sure give me sometime.

**Comment by ludbek** [comment]
Its done.

**Comment by cs01** [comment]
Thank you

**Comment by ludbek** [comment]
@cs01  make sure to start the package version with `1.0` cos I am pretty sure `khalti`'s pipeline uses it for one of its projects.

**Comment by cs01** [comment]
The latest version of pipx on PyPI is 0.1.1. 

pipx-app is at 0.11.0.2. Is there a reason I should bump to 1.0 rather than continue on from 0.11?

**Comment by ludbek** [comment]
I'll pin the version. You continue with your desired version.
